// app/src/pages/LogIn.svelte
<script lang="ts">
	//@ts-nocheck
	import { Button } from "$lib/components/ui/button";
	import * as Card from "$lib/components/ui/card";
	import { Input } from "$lib/components/ui/input";
	import { Label } from "$lib/components/ui/label";
	import { user } from "$lib/stores/userStore";
	import { navigate } from "svelte-routing";
	import { writable } from "svelte/store";
	import { z } from "zod";
	import { account } from "../../appwrite";

	const schema = z.object({
		email: z.string().email("input a valid e-mail"),
		password: z
			.string()
			.min(8, { message: "Must have at least 8 characters" }),
	});

	function normalize(error) {
		const errors = { email: [], password: [] };

		error.forEach((err) => {
			errors[err.path[0]].push(err.message);
		});

		return errors;
	}

	async function login() {
		try {
			schema.parse($credentials);
			try {
				await account.createEmailPasswordSession(
					$credentials.email,
					$credentials.password,
				);
				navigate("/");
			} catch (e) {
				$errors.email = ["incorrect email or password"];
				$errors.password = ["incorrect email or password"];
			}
		} catch (error) {
			$errors = normalize(JSON.parse(error.message));
		}
	}

	const errors = writable({});
	const credentials = writable({
		email: "",
		password: "",
	});

	$: $user.data !== undefined && navigate("/");
</script>

<Card.Root
	class="absolute -translate-y-1/2 -translate-x-1/2 left-1/2 top-1/2 w-[90svw] md:w-2/6 md:min-w-[400px]"
>
	<Card.Header>
		<Card.Title>Log in</Card.Title>
		<Card.Description>
			Enter your credentials to log in to the system
		</Card.Description>
	</Card.Header>
	<Card.Content class="grid gap-5">
		<div class="flex flex-col space-y-1.5">
			<span class="flex gap-4">
				<Label for="email">Email</Label>
				<p
					class={`text-xs text-red-400 ${($errors?.email?.[0] && "visible") || "invisible size-0"} my-auto h-fit m-0 p-0`}
				>
					{$errors?.email?.[0]}
				</p>
			</span>
			<Input
				id="email"
				type="email"
				placeholder="max@example.com"
				value={$credentials.email}
				on:input={(e) => ($credentials.email = e.target?.value)}
			/>
		</div>
		<div class="flex flex-col space-y-1.5">
			<span class="flex gap-4">
				<Label for="email">Password</Label>
				<p
					class={`text-xs text-red-400 ${($errors?.password?.[0] && "visible") || "invisible size-0"} my-auto h-fit m-0 p-0`}
				>
					{$errors?.password?.[0]}
				</p>
			</span>
			<Input
				id="pass"
				type="password"
				placeholder="max123"
				value={$credentials.password}
				on:input={(e) => ($credentials.password = e.target?.value)}
			/>
		</div>
		<div class="flex justify-between gap-5">
			<span class="flex h-fit gap-1 my-auto">
				<p class="text-xs mt-auto">Don't have an account?</p>

				<!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
				<!-- svelte-ignore a11y-click-events-have-key-events -->
				<p
					on:click={() => navigate("/Signup")}
					class="text-sm h-min font-semibold mt-auto cursor-pointer"
				>
					Sign up
				</p>
			</span>

			<Button class="font-bold" variant="outline" on:click={login}>
				Log in
			</Button>
		</div>
	</Card.Content>
</Card.Root>

// app/src/pages/Login.jsx
import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "../components/ui/button";
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Toaster } from "../components/ui/toaster";
import { useToast } from "../components/ui/use-toast";
import useUserStore from "../stores/userStore";
import pb from "../pb";

export function Login() {
    const { user, log } = useUserStore();
    const { toast } = useToast();
    const navigate = useNavigate();
    const [credentials, setCredentials] = useState({
        identity: "",
        password: "",
    });

    const change = useCallback(
        (e) =>
            setCredentials((s) => ({ ...s, [e.target.name]: e.target.value })),
        []
    );

    const login = useCallback(() => {
        (async () => {
            try {
                await pb
                    .collection("users")
                    .authWithPassword(
                        credentials.identity,
                        credentials.password
                    );

                log();
            } catch (error) {
                console.error("error logging user: ", error.message);
                toast({
                    title: "Error",
                    description: error.message,
                });
            }
        })();
    }, [credentials, log, toast]);

    useEffect(() => {
        user && navigate("/");
    }, [user, navigate]);

    return (
        <>
            <div className="absolute inset-0 flex items-center justify-center">
                <Card className="max-w-1/4 min-w-fit">
                    <CardHeader>
                        <CardTitle className="text-2xl">Login</CardTitle>
                        <CardDescription>
                            Enter your email below to login to your account.
                        </CardDescription>
                    </CardHeader>
                    <CardContent className="grid gap-4">
                        <div className="grid gap-2">
                            <Label htmlFor="email">Username or Email</Label>
                            <Input
                                type="text"
                                name="identity"
                                onChange={change}
                                value={credentials.email}
                                placeholder="Max or m@example.com"
                                required
                            />
                        </div>
                        <div className="grid gap-2">
                            <Label htmlFor="password">Password</Label>
                            <Input
                                type="password"
                                name="password"
                                onChange={change}
                                value={credentials.password}
                                required
                            />
                        </div>
                    </CardContent>
                    <CardFooter className="grid grid-cols-2 gap-2">
                        <Button
                            onClick={login}
                            className="w-full text-lg"
                            variant="secondary">
                            Log in
                        </Button>
                        <p className="text-sm ml-auto">
                            Have an account?
                            <a
                                className="text-md ml-0.5 italic font-bold underline cursor-pointer"
                                onClick={() => navigate("/Signup")}>
                                Sign up
                            </a>
                        </p>
                    </CardFooter>
                </Card>
            </div>
            <Toaster />
        </>
    );
}
export default Login;
