// app/src/pages/SignUp.svelte
<script lang="ts">
	//@ts-nocheck

	import PasswordStrength from "$lib/components/PasswordStrength.svelte";
	import { Button } from "$lib/components/ui/button";
	import * as Card from "$lib/components/ui/card";
	import { Input } from "$lib/components/ui/input";
	import { Label } from "$lib/components/ui/label";
	import { user } from "$lib/stores/userStore";
	import { navigate } from "svelte-routing";
	import { writable } from "svelte/store";
	import { z } from "zod";
	import { account } from "../../appwrite";
	import { v4 as uuidv4 } from "uuid";
	import Loader from "$lib/components/Loader.svelte";

	// Minimum 8 characters, at least one uppercase letter, one lowercase letter, one number and one special character
	const passwordValidation = new RegExp(
		/^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$/,
	);
	const schema = z.object({
		email: z.string().email("input a valid e-mail"),
		password: z.string().min(8).regex(passwordValidation),
	});

	function normalize(error) {
		const errors = { email: [], password: [] };

		error.forEach((err) => {
			errors[err.path[0]].push(err.message);
		});

		return errors;
	}

	async function signup() {
		try {
			schema.parse($credentials);
			console.log($credentials);
			$load = true;
			try {
				await account.create(
					uuidv4(),
					$credentials.email,
					$credentials.password,
				);
				navigate("/Login");
			} catch (e) {
				$load = false;
				console.log(e.message);
				$errors.email = ["Email already in use"];
			}
		} catch (error) {
			$errors = normalize(JSON.parse(error.message));
		}
	}

	const load = writable(false);
	const errors = writable({});
	const credentials = writable({
		email: "",
		password: "",
	});

	$: $user.data !== undefined && navigate("/");
</script>

{#if $load}
	<Loader />
{:else}
	<Card.Root
		class="absolute -translate-y-1/2 -translate-x-1/2 left-1/2 top-1/2 w-[90svw] md:w-2/6 md:min-w-[400px]"
	>
		<Card.Header>
			<Card.Title>Sign up</Card.Title>
			<Card.Description>
				Enter your credentials to create an account
			</Card.Description>
		</Card.Header>
		<Card.Content class="grid gap-5">
			<div class="flex flex-col space-y-1.5">
				<span class="flex gap-4">
					<Label for="email">Email</Label>
					<p
						class={`text-xs text-red-400 my-auto h-fit m-0 p-0 ${($errors?.email?.[0] && "visible") || "invisible size-0"}`}
					>
						{$errors?.email?.[0]}
					</p>
				</span>
				<Input
					id="email"
					type="email"
					placeholder="max@example.com"
					value={$credentials.email}
					on:input={(e) => ($credentials.email = e.target?.value)}
				/>
			</div>
			<div class="flex flex-col space-y-1.5">
				<span class="flex gap-4">
					<Label for="email">Password</Label>
				</span>
				<Input
					id="pass"
					type="password"
					placeholder="max123"
					value={$credentials.password}
					on:input={(e) => ($credentials.password = e.target?.value)}
				/>
				<PasswordStrength bind:password={$credentials.password} />
			</div>
			<div class="flex justify-between gap-5">
				<span class="flex h-fit gap-1 my-auto">
					<p class="text-xs mt-auto">Have an account?</p>

					<!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
					<!-- svelte-ignore a11y-click-events-have-key-events -->
					<p
						on:click={() => navigate("/Login")}
						class="text-sm h-min font-semibold mt-auto cursor-pointer"
					>
						Log in
					</p>
				</span>

				<Button class="font-bold" variant="outline" on:click={signup}>
					Sign up
				</Button>
			</div>
		</Card.Content>
	</Card.Root>
{/if}

// app/src/pages/Signup.jsx
import { useCallback, useEffect, useState } from "react";
import { Toaster } from "../components/ui/toaster";
import { Button } from "../components/ui/button";
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import pb from "../pb";
import useUserStore from "../stores/userStore";
import { useNavigate } from "react-router-dom";
import { useToast } from "../components/ui/use-toast";

export function Signup() {
    const user = useUserStore((s) => s.user);
    const navigate = useNavigate();
    const { toast } = useToast();

    const [credentials, setCredentials] = useState({
        username: "",
        email: "",
        password: "",
        first_name: "",
        last_name: "",
        professor: false,
        emailVisibility: true,
    });

    const change = useCallback(
        (e) =>
            setCredentials((s) => ({ ...s, [e.target.name]: e.target.value })),
        [setCredentials]
    );

    useEffect(
        () =>
            console.table({
                ...credentials,
                passwordConfirm: credentials.password,
            }),
        [credentials]
    );

    useEffect(() => {
        user && navigate("/");
    }, [user, navigate]);

    const sign = useCallback(async () => {
        try {
            await pb.collection("users").create({
                ...credentials,
                passwordConfirm: credentials.password,
            });

            navigate("/Login");
        } catch (error) {
            toast({
                title: "Error",
                description: error.message,
            });
        }
    }, [credentials, toast, navigate]);

    return (
        <>
            <div className=" absolute inset-0 flex items-center justify-center">
                <Card className="max-w-1/4 min-w-fit">
                    <CardHeader>
                        <CardTitle className="text-2xl">Sign up</CardTitle>
                        <CardDescription>
                            Enter your data bellow to create an account.
                        </CardDescription>
                    </CardHeader>
                    <CardContent className="grid gap-4">
                        <div className="grid grid-cols-2 gap-1">
                            <div className="grid2 gap-4">
                                <Label htmlFor="first-name">First name</Label>
                                <Input
                                    id="first-name"
                                    name="first_name"
                                    value={credentials.first_name}
                                    onChange={change}
                                    placeholder="Max"
                                    required
                                />
                            </div>
                            <div className="grid gap-2">
                                <Label htmlFor="last-name">Last name</Label>
                                <Input
                                    id="last-name"
                                    name="last_name"
                                    value={credentials.last_name}
                                    onChange={change}
                                    placeholder="Robinson"
                                    required
                                />
                            </div>
                        </div>
                        <div className="grid gap-1">
                            <Label htmlFor="username">Username</Label>
                            <Input
                                type="text"
                                name="username"
                                value={credentials.username}
                                onChange={change}
                                placeholder="Max"
                                required
                            />
                        </div>
                        <div className="grid gap-1">
                            <Label htmlFor="email">Email</Label>
                            <Input
                                type="email"
                                name="email"
                                value={credentials.email}
                                onChange={change}
                                placeholder="m@example.com"
                                required
                            />
                        </div>
                        <div className="grid gap-1">
                            <Label htmlFor="password">Password</Label>
                            <Input
                                type="password"
                                name="password"
                                value={credentials.password}
                                onChange={change}
                                required
                            />
                        </div>
                    </CardContent>
                    <CardFooter className="grid gap-2 grid-cols-2">
                        <Button
                            className="w-full text-lg"
                            variant="secondary"
                            onClick={sign}>
                            Sign up
                        </Button>

                        <p className="text-sm ml-auto">
                            Not registered?
                            <a
                                className="text-md ml-0.5 italic font-bold underline cursor-pointer"
                                onClick={() => navigate("/Login")}>
                                Log in
                            </a>
                        </p>
                    </CardFooter>
                </Card>
            </div>
            <Toaster />
        </>
    );
}
export default Signup;
